### ISSUE TITLE
Error trainig normal model

### ISSUE THREAD

**Issue by OzoneAsai** [litagin02/Style-Bert-VITS2#100]
```
Error: 学習に失敗しました:
Traceback (most recent call last):
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\style_bert_vits2\models\utils\checkpoints.py", line 198, in get_latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\train_ms_jp_extra.py", line 404, in run
    utils.checkpoints.get_latest_checkpoint_path(
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\style_bert_vits2\models\utils\checkpoints.py", line 200, in get_latest_checkpoint_path
    raise ValueError(f"No checkpoint found in {model_dir_path} with regex {regex}")
ValueError: No checkpoint found in Data\EnTest\models with regex WD_*.pth

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\train_ms_jp_extra.py", line 1113, in <module>
    run()
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\train_ms_jp_extra.py", line 416, in run
    optim_wd.param_groups[0]["initial_lr"] = wd_resume_lr
UnboundLocalError: local variable 'wd_resume_lr' referenced before assignment
```

**Comment by litagin02** [comment]
normal modelとはJP-Extra版でないモデルということでしょうか？
その場合は「JP-Extra版を使う」のチェックを外して（train_ms.pyのほうを）実行する必要があります。

**Comment by OzoneAsai** [comment]
```json
{
  "model_name": "EnTest",
  "train": {
    "log_interval": 10,
    "eval_interval": 1400,
    "seed": 42,
    "epochs": 120,
    "learning_rate": 0.0002,
    "betas": [
      0.8,
      0.99
    ],
    "eps": 1e-09,
    "batch_size": 1,
    "bf16_run": false,
    "lr_decay": 0.99995,
    "segment_size": 16384,
    "init_lr_ratio": 1,
    "warmup_epochs": 0,
    "c_mel": 45,
    "c_kl": 1.0,
    "skip_optimizer": false,
    "freeze_ZH_bert": false,
    "freeze_JP_bert": false,
    "freeze_EN_bert": false,
    "freeze_style": false,
    "freeze_encoder": false,
    "freeze_decoder": false
  },
  "data": {
    "use_jp_extra": false,
    "training_files": "Data\\EnTest\\train.list",
    "validation_files": "Data\\EnTest\\val.list",
    "max_wav_value": 32768.0,
    "sampling_rate": 44100,
    "filter_length": 2048,
    "hop_length": 512,
    "win_length": 2048,
    "n_mel_channels": 128,
    "mel_fmin": 0.0,
    "mel_fmax": null,
    "add_blank": true,
    "n_speakers": 1,
    "cleaned_text": true,
    "num_styles": 1,
    "style2id": {
      "Neutral": 0
    },
    "spk2id": {
      "EnTest": 0
    }
  },
  "model": {
    "use_spk_conditioned_encoder": true,
    "use_noise_scaled_mas": true,
    "use_mel_posterior_encoder": false,
    "use_duration_discriminator": true,
    "inter_channels": 192,
    "hidden_channels": 192,
    "filter_channels": 768,
    "n_heads": 2,
    "n_layers": 6,
    "kernel_size": 3,
    "p_dropout": 0.1,
    "resblock": "1",
    "resblock_kernel_sizes": [
      3,
      7,
      11
    ],
    "resblock_dilation_sizes": [
      [
        1,
        3,
        5
      ],
      [
        1,
        3,
        5
      ],
      [
        1,
        3,
        5
      ]
    ],
    "upsample_rates": [
      8,
      8,
      2,
      2,
      2
    ],
    "upsample_initial_channel": 512,
    "upsample_kernel_sizes": [
      16,
      16,
      8,
      2,
      2
    ],
    "n_layers_q": 3,
    "use_spectral_norm": false,
    "gin_channels": 256
  },
  "version": "2.4.0"
}
```

**Comment by OzoneAsai** [comment]
Configの複製です。JP_Extraでないモデルということですね

**Comment by litagin02** [comment]
エラーは解決しましたでしょうか？（WebUIからは「JP-Extraを使う」のチェックを外して実行すれば、train_ms_jp_extra.pyではなくtrain_ms.pyが実行されてエラーが解決するはずです）

**Comment by OzoneAsai** [comment]
.....Configを参照しないんですか？

**Comment by litagin02** [comment]
実行するスクリプトファイルが違うので、WebUIのチェックボックスからどちらのファイルを学習するかを決定する挙動になっています。

**Comment by OzoneAsai** [comment]
解決はしたので、クローズします。
