### ISSUE TITLE
データセット作成の文字起こしの際にエラーが出る

### ISSUE THREAD

**Issue by miikichi** [litagin02/Style-Bert-VITS2#153]
最近新しくPCを購入し、新しいPCでもStyle-Bert-VITS2を使おうとして
データセット作成の文字起こしを使用しようとした際にエラーが出る用になりました。
最新版の2.6.0や2.5.0で起こりました。
```
07-18 00:22:18 |  INFO  | subprocess.py:23 | Running: transcribe.py --model_name test --model large-v3 --compute_type bfloat16 --language ja --initial_prompt "こんにちは。元気、ですかー？ふふっ、私は……ちゃんと元気だよ！" --num_beams 1 --use_hf_whisper --batch_size 16
07-18 00:22:20 |  INFO  | transcribe.py:203 | Loading HF Whisper model (openai/whisper-large-v3)
  0%|                                                                                          | 0/108 [00:00<?, ?it/s]07-18 00:22:22 |  INFO  | transcribe.py:70 | generate_kwargs: {'language': 'ja', 'do_sample': False, 'num_beams': 1, 'no_repeat_ngram_size': 10}
Traceback (most recent call last):
  File "D:\AI-Workspaces\ProgramFiles\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\AI-Workspaces\ProgramFiles\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\AI-Workspaces\ProgramFiles\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\gradio\blocks.py", line 1897, in process_api
    result = await self.call_function(
  File "D:\AI-Workspaces\ProgramFiles\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\gradio\blocks.py", line 1483, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI-Workspaces\ProgramFiles\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\AI-Workspaces\ProgramFiles\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\AI-Workspaces\ProgramFiles\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\AI-Workspaces\ProgramFiles\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\gradio\utils.py", line 816, in wrapper
    response = f(*args, **kwargs)
  File "D:\AI-Workspaces\ProgramFiles\Style-Bert-VITS2\Style-Bert-VITS2\gradio_tabs\dataset.py", line 75, in do_transcribe
    success, message = run_script_with_log(cmd, ignore_warning=True)
  File "D:\AI-Workspaces\ProgramFiles\Style-Bert-VITS2\Style-Bert-VITS2\style_bert_vits2\utils\subprocess.py", line 24, in run_script_with_log
    result = subprocess.run(
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 1144, in communicate
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1009: invalid start byte
```

他にも、Dataset.batを起動する際に、以下のようなエラーが出ました。
```
Running gradio_tabs/dataset.py...
Traceback (most recent call last):
  File "D:\AI-Workspaces\ProgramFiles\Style-Bert-VITS2\Style-Bert-VITS2\gradio_tabs\dataset.py", line 3, in <module>
    from style_bert_vits2.constants import GRADIO_THEME
ModuleNotFoundError: No module named 'style_bert_vits2'
```
以前のPC同様、CUDAやcuDNNの設定などはしているはずなのですが、何故かエラーを出されて困惑しています。
なにか他処方はあるのでしょうか？
CUDAは12.1、cuDNNは8.7.9を使用しています。

**Comment by litagin02** [comment]
ffmpegは入っているでしょうか？

**Comment by miikichi** [comment]
あーもしかしたら入れてない可能性ありそうです。
入ってなかったら今ffmpeg入れて試してみます

**Comment by miikichi** [comment]
> ffmpegは入っているでしょうか？

インストールされてなかったのでインストールした結果、
App.batでのデータセット作成での文字起こしは成功しました。
```
07-19 17:13:13 |  INFO  | subprocess.py:23 | Running: transcribe.py --model_name test --model large-v3 --compute_type bfloat16 --language ja --initial_prompt "こんにちは。元気、ですかー？ふふっ、私は……ちゃんと元気だよ！" --num_beams 1 --use_hf_whisper --batch_size 16
07-19 17:13:14 |  INFO  | transcribe.py:203 | Loading HF Whisper model (openai/whisper-large-v3)
  0%|                                                                                          | 0/108 [00:00<?, ?it/s]07-19 17:13:17 |  INFO  | transcribe.py:70 | generate_kwargs: {'language': 'ja', 'do_sample': False, 'num_beams': 1, 'no_repeat_ngram_size': 10}
100%|████████████████████████████████████████████████████████████████████████████████| 108/108 [00:27<00:00,  3.86it/s]
07-19 17:13:43 |SUCCESS | subprocess.py:38 | Success: transcribe.py --model_name test --model large-v3 --compute_type bfloat16 --language ja --initial_prompt "こんにちは。元気、ですかー？ふふっ、私は……ちゃんと元気だよ！" --num_beams 1 --use_hf_whisper --batch_size 16
```

ですが、**何故か**Dataset.batでは同じエラーが出てしまいます。
```
Running gradio_tabs/dataset.py...
Traceback (most recent call last):
  File "D:\AI-Workspaces\ProgramFiles\Style-Bert-VITS2\Style-Bert-VITS2\gradio_tabs\dataset.py", line 3, in <module>
    from style_bert_vits2.constants import GRADIO_THEME
ModuleNotFoundError: No module named 'style_bert_vits2'
Press any key to continue . . .
```

**Comment by litagin02** [comment]
すみません原因はもしかしたら思いつくものはありますが、まだ試していないので、とりあえずはDataset.batは使わずに試していただけますでしょうか。
（もともとDataset.bat等は無くしてすべてApp.batに統一しているので、機能面での差はないはずです。）

**Comment by miikichi** [comment]
分かりました。ありがとうございます。
