### ISSUE TITLE
OSERORR:{WinError 126}指定されたモジュールが見つかりません。といったエラーが出てきてしまい、インストールに失敗しました。

### ISSUE THREAD

**Issue by keisasa00** [litagin02/Style-Bert-VITS2#155]

**Comment by ochiainobuto** [comment]
わたしのところも同じです。エラーは下記です。
OSError: [WinError 126] 指定されたモジュールが見つかりません。 Error loading "C:\Users\cxcgp\OneDrive\デスクトップ\sbv2\Style-Bert-VITS2\venv\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by keisasa00** [comment]
https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969/9
つまり、基本「Visual C++ 再頒布可能パッケージ」を自分の、環境に合わせてインストールすると解決できるようです。
それでも解決しない場合、https://hourouneko.hateblo.jp/entry/2022/10/12/113642
ファイルが参照している他の.dllの参照先が増えことが原因のようですので、
Dependencies_x64_Release.zipをダウンロードし、[ 184](https://github.com/lucasg/Dependencies/releases/tag/v1.11.1)または、32 ビットの場合は x86 で、DependenciesGui.exe を解凍して開き、fbgemm.dll を開くと、失われたファイルが表示されるようです、その後、失われたファイルを fbgemm.dll と同じフォルダーにダウンロードし、コードを再度実行するといいそうです、自分は、失われたファイルを特定することはできましたが、それがどこでダウンロード出来るか分からないでいます。

**Comment by keisasa00** [comment]
https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependency-is-missing/201969/9
基本的に「Visual C++ 再頒布可能」 「パッケージ」を自分の、環境に合わせてインストールすると解決できるようです。
それでも解決しない場合、https://hourouneko.hateblo.jp/entry/2022/10/12/113642
ファイルが参照している他の。 dll の参照先が増えることが原因のようですので、
Dependency_x64_Release.zip をダウンロードし、184または、32 ビットの場合は x86 で、DependencyGui.exe を見つけて開く、fbgemm.dll を開くと、失われたファイルが表示されるようです、その後、失われたファイルを fbgemm.dll と同じ場所にダウンロードし、コードをもう一度実行したらいいそうです、

libomp140.x86_64.dllが失われたファイルならば、
https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d/download
上記のサイトでダウンロードできます。

自動ダウンロードですので、ダウンロードが始まったらすぐに、ダウンロードしたフォルダーごとではなく、libomp140.x86_64.dllファイルをlibフォルダー内に入れる必要があります。

＊このやり方では不具合が別のところで起こる可能性もあるようです。

本質的に問題のない解決策としては、
インストール時に、torch のバージョンを指定して古いものを使うようにするのがベターで、バッチファイルのtorchをインストールしている部分とか、requirements*.txt とかをいじればいいよく、自動インストールではgithubのレポジトリをcloneして実行しているので、管理者さんの対応を待つか、自分でひとつずつ手動で実行するかだそうです。

（自分は、githubがわかりませんので、このやり方は取れませんでした。）

**Comment by litagin02** [comment]
PyTorchが最近2.4にアップデートされたのが原因かもしれません。
そこを修正して新しく
https://github.com/litagin02/Style-Bert-VITS2/releases/download/2.6.0/sbv2.zip
を作りましたので、新しくこちらを使ってインストールを試みてくださると助かります。

**Comment by keisasa00** [comment]
> [PyTorch が最近](https://github.com/litagin02/Style-Bert-VITS2/releases/download/2.6.0/sbv2.zip)2.4 にアップデートされたのが原因かもしれませ ん 。作りましたので、新しくここを使ってインストールを試みて協力していただきます。 [](https://github.com/litagin02/Style-Bert-VITS2/releases/download/2.6.0/sbv2.zip)

早速のご対応ありがとうございます。

**Comment by ochiainobuto** [comment]
ありがとうございます。早速、
https://github.com/litagin02/Style-Bert-VITS2/releases/download/2.6.0/sbv2.zip
こちらでインストールしてみたのですが、モデルのダウンロードの後ストップしてしまいます。

----------------------------------------
Model download is complete. Start Style-Bert-VITS2 Editor.
----------------------------------------
Executing: python server_editor.py --inbrowser
07-29 15:53:34 | DEBUG  | __init__.py:92 | try starting pyopenjtalk worker server
07-29 15:53:36 | DEBUG  | __init__.py:130 | pyopenjtalk worker server started
Error: Failed to update dictionary.
Traceback (most recent call last):
  File "C:\Users\cxcgp\OneDrive\デスクトップ\sbv2\Style-Bert-VITS2\style_bert_vits2\nlp\japanese\user_dict\__init__.py", line 150, in update_dict
    pyopenjtalk.unset_user_dict()
  File "C:\Users\cxcgp\OneDrive\デスクトップ\sbv2\Style-Bert-VITS2\style_bert_vits2\nlp\japanese\pyopenjtalk_worker\__init__.py", line 66, in unset_user_dict
    WORKER_CLIENT.dispatch_pyopenjtalk("unset_user_dict")
  File "C:\Users\cxcgp\OneDrive\デスクトップ\sbv2\Style-Bert-VITS2\style_bert_vits2\nlp\japanese\pyopenjtalk_worker\worker_client.py", line 41, in dispatch_pyopenjtalk
    response = receive_data(self.sock)
  File "C:\Users\cxcgp\OneDrive\デスクトップ\sbv2\Style-Bert-VITS2\style_bert_vits2\nlp\japanese\pyopenjtalk_worker\worker_common.py", line 42, in receive_data
    header = __receive_until(sock, HEADER_SIZE)
  File "C:\Users\cxcgp\OneDrive\デスクトップ\sbv2\Style-Bert-VITS2\style_bert_vits2\nlp\japanese\pyopenjtalk_worker\worker_common.py", line 35, in __receive_until
    raise ConnectionClosedException("接続が閉じられました")
style_bert_vits2.nlp.japanese.pyopenjtalk_worker.worker_common.ConnectionClosedException: 接続が閉じられました
Traceback (most recent call last):
  File "C:\Users\cxcgp\OneDrive\デスクトップ\sbv2\Style-Bert-VITS2\server_editor.py", line 157, in <module>
    update_dict()
  File "C:\Users\cxcgp\OneDrive\デスクトップ\sbv2\Style-Bert-VITS2\style_bert_vits2\nlp\japanese\user_dict\__init__.py", line 159, in update_dict
    raise e
  File "C:\Users\cxcgp\OneDrive\デスクトップ\sbv2\Style-Bert-VITS2\style_bert_vits2\nlp\japanese\user_dict\__init__.py", line 150, in update_dict
    pyopenjtalk.unset_user_dict()
  File "C:\Users\cxcgp\OneDrive\デスクトップ\sbv2\Style-Bert-VITS2\style_bert_vits2\nlp\japanese\pyopenjtalk_worker\__init__.py", line 66, in unset_user_dict
    WORKER_CLIENT.dispatch_pyopenjtalk("unset_user_dict")
  File "C:\Users\cxcgp\OneDrive\デスクトップ\sbv2\Style-Bert-VITS2\style_bert_vits2\nlp\japanese\pyopenjtalk_worker\worker_client.py", line 41, in dispatch_pyopenjtalk
    response = receive_data(self.sock)
  File "C:\Users\cxcgp\OneDrive\デスクトップ\sbv2\Style-Bert-VITS2\style_bert_vits2\nlp\japanese\pyopenjtalk_worker\worker_common.py", line 42, in receive_data
    header = __receive_until(sock, HEADER_SIZE)
  File "C:\Users\cxcgp\OneDrive\デスクトップ\sbv2\Style-Bert-VITS2\style_bert_vits2\nlp\japanese\pyopenjtalk_worker\worker_common.py", line 35, in __receive_until
    raise ConnectionClosedException("接続が閉じられました")
style_bert_vits2.nlp.japanese.pyopenjtalk_worker.worker_common.ConnectionClosedException: 接続が閉じられました
07-29 15:53:39 | DEBUG  | __init__.py:147 | pyopenjtalk worker server terminated
07-29 15:53:39 | ERROR  | __init__.py:157 | [WinError 10053] 確立された接続がホスト コンピューターのソウトウェアによって中止されました。

**Comment by litagin02** [comment]
直接の原因かは分かりませんが、保存されている場所に「デスクトップ」という日本語があることが悪さをしているかもしれませんので、別の場所にインストールして試してもらえますでしょうか。

**Comment by ochiainobuto** [comment]
Cドライブでインストール＆起動できました！お騒がせしました、ありがとうございます。
