### ISSUE TITLE
Training Failed

### ISSUE THREAD

**Issue by OzoneAsai** [litagin02/Style-Bert-VITS2#162]
```
Running app.py...
D:\Workspace\sbv2\Style-Bert-VITS2\venv\lib\site-packages\transformers\utils\hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
09-10 18:01:34 | DEBUG  | __init__.py:92 | try starting pyopenjtalk worker server
09-10 18:01:35 | DEBUG  | __init__.py:130 | pyopenjtalk worker server started
09-10 18:01:40 |WARNING | tts_model.py:397 | No model files found in model_assets\.cache, so skip it
09-10 18:01:40 |WARNING | tts_model.py:397 | No model files found in model_assets\gem2022M, so skip it
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
09-10 18:02:09 |  INFO  | subprocess.py:23 | Running: train_ms.py --config Data\gem2022M\config.json --model Data\gem2022M
09-10 18:02:13 |  INFO  | train_ms.py:116 | Loading configuration from config 0
09-10 18:02:13 |  INFO  | train_ms.py:116 | Loading configuration from config localhost
09-10 18:02:13 |  INFO  | train_ms.py:116 | Loading configuration from config 10086
09-10 18:02:13 |  INFO  | train_ms.py:116 | Loading configuration from config 0
09-10 18:02:13 |  INFO  | train_ms.py:116 | Loading configuration from config 1
09-10 18:02:13 |  INFO  | train_ms.py:118 | Loading environment variables
MASTER_ADDR: localhost,
MASTER_PORT: 10086,
WORLD_SIZE: 1,
RANK: 0,
LOCAL_RANK: 0
09-10 18:02:13 |  INFO  | default_style.py:54 | At least 2 subdirectories are required for generating style vectors with respect to them, found 0.
09-10 18:02:13 |  INFO  | default_style.py:57 | Generating only neutral style vector instead.
09-10 18:02:13 |  INFO  | default_style.py:28 | Saved mean style vector to model_assets\gem2022M
09-10 18:02:13 |  INFO  | default_style.py:36 | Saved style config to model_assets\gem2022M\config.json
09-10 18:02:14 | ERROR  | subprocess.py:33 | Error: train_ms.py --config Data\gem2022M\config.json --model Data\gem2022M
[rank0]: Traceback (most recent call last):
[rank0]:   File "D:\Workspace\sbv2\Style-Bert-VITS2\train_ms.py", line 986, in <module>
[rank0]:     run()
[rank0]:   File "D:\Workspace\sbv2\Style-Bert-VITS2\train_ms.py", line 208, in run
[rank0]:     torch.cuda.set_device(local_rank)
[rank0]:   File "D:\Workspace\sbv2\Style-Bert-VITS2\venv\lib\site-packages\torch\cuda\__init__.py", line 399, in set_device
[rank0]:     torch._C._cuda_setDevice(device)
[rank0]: AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

09-10 18:02:14 | ERROR  | train.py:360 | Train failed.

```
```
Package                 Version
----------------------- ------------
absl-py                 2.1.0
aiofiles                23.2.1
aiohappyeyeballs        2.4.0
aiohttp                 3.10.5
aiosignal               1.3.1
alembic                 1.13.2
annotated-types         0.7.0
antlr4-python3-runtime  4.9.3
anyio                   4.4.0
asteroid-filterbanks    0.4.0
async-timeout           4.0.3
attrs                   24.2.0
audioread               3.0.1
av                      10.0.0
certifi                 2024.8.30
cffi                    1.17.1
charset-normalizer      3.3.2
click                   8.1.7
cmudict                 1.0.30
cn2an                   0.5.22
colorama                0.4.6
coloredlogs             15.0.1
colorlog                6.8.2
contourpy               1.3.0
ctranslate2             3.24.0
cycler                  0.12.1
Cython                  3.0.11
decorator               5.1.1
Distance                0.1.3
docopt                  0.6.2
einops                  0.8.0
exceptiongroup          1.2.2
fastapi                 0.112.4
faster-whisper          0.10.1
ffmpeg-python           0.2.0
ffmpy                   0.4.0
filelock                3.16.0
flatbuffers             24.3.25
fonttools               4.53.1
frozenlist              1.4.1
fsspec                  2024.9.0
future                  1.0.0
g2p-en                  2.1.0
GPUtil                  1.4.0
gradio                  4.43.0
gradio_client           1.3.0
greenlet                3.0.3
grpcio                  1.66.1
h11                     0.14.0
httpcore                1.0.5
httpx                   0.27.2
huggingface-hub         0.24.6
humanfriendly           10.0
HyperPyYAML             1.2.2
idna                    3.8
importlib_metadata      8.4.0
importlib_resources     6.4.5
inflect                 7.4.0
intel-openmp            2021.4.0
jieba                   0.42.1
Jinja2                  3.1.4
joblib                  1.4.2
julius                  0.2.7
kiwisolver              1.4.7
librosa                 0.9.2
lightning               2.4.0
lightning-utilities     0.11.7
llvmlite                0.43.0
loguru                  0.7.2
Mako                    1.3.5
Markdown                3.7
markdown-it-py          3.0.0
MarkupSafe              2.1.5
matplotlib              3.9.2
mdurl                   0.1.2
mkl                     2021.4.0
more-itertools          10.5.0
mpmath                  1.3.0
multidict               6.1.0
networkx                3.3
nltk                    3.9.1
num2words               0.5.13
numba                   0.60.0
numpy                   1.26.4
omegaconf               2.3.0
onnxruntime             1.19.2
openai-whisper          20230124
optuna                  4.0.0
orjson                  3.10.7
packaging               24.1
pandas                  2.2.2
pillow                  10.4.0
pip                     24.1.2
platformdirs            4.3.2
pooch                   1.8.2
primePy                 1.3
proces                  0.1.7
protobuf                4.25.0
psutil                  6.0.0
punctuators             0.0.7
pyannote.audio          3.3.1
pyannote.core           5.0.0
pyannote.database       5.1.0
pyannote.metrics        3.2.1
pyannote.pipeline       3.0.1
pycparser               2.22
pydantic                2.9.1
pydantic_core           2.23.3
pydub                   0.25.1
Pygments                2.18.0
pyloudnorm              0.1.1
pynndescent             0.5.13
pyopenjtalk-dict        0.3.4.dev2
pyparsing               3.1.4
pypinyin                0.52.0
pyreadline3             3.4.1
python-dateutil         2.9.0.post0
python-multipart        0.0.9
pytorch-lightning       2.4.0
pytorch-metric-learning 2.6.0
pytz                    2024.1
pyworld-prebuilt        0.3.4.1
PyYAML                  6.0.2
regex                   2024.7.24
requests                2.32.3
resampy                 0.4.3
rich                    13.8.0
ruamel.yaml             0.18.6
ruamel.yaml.clib        0.2.8
ruff                    0.6.4
safetensors             0.4.5
scikit-learn            1.5.1
scipy                   1.14.1
semantic-version        2.10.0
semver                  3.0.2
sentencepiece           0.2.0
setuptools              74.1.2
shellingham             1.5.4
six                     1.16.0
sniffio                 1.3.1
sortedcontainers        2.4.0
soundfile               0.12.1
speechbrain             1.0.1
SQLAlchemy              2.0.34
stable-ts               1.4.0
starlette               0.38.5
sympy                   1.13.2
tabulate                0.9.0
tbb                     2021.13.1
tensorboard             2.17.1
tensorboard-data-server 0.7.2
tensorboardX            2.6.2.2
threadpoolctl           3.5.0
tokenizers              0.15.2
tomlkit                 0.12.0
torch                   2.3.1
torch-audiomentations   0.11.1
torch-pitch-shift       1.2.4
torchaudio              2.3.1
torchmetrics            1.4.1
torchvision             0.19.1+cu124
tqdm                    4.66.5
transformers            4.39.3
typeguard               4.3.0
typer                   0.12.5
typing_extensions       4.12.2
tzdata                  2024.1
umap-learn              0.5.6
urllib3                 2.2.2
uv                      0.4.8
uvicorn                 0.30.6
websockets              12.0
Werkzeug                3.0.4
wheel                   0.43.0
win32-setctime          1.1.0
yarl                    1.11.1
zipp                    3.20.1
```

**Comment by OzoneAsai** [comment]
```
PS D:\Workspace\sbv2\Style-Bert-VITS2> python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.cuda.is_available())
False
![image](https://github.com/user-attachments/assets/ab799e85-5650-4f1d-b0bb-b1776ce40d2c)
![image](https://github.com/user-attachments/assets/7d92c282-9f3a-4037-a561-9b3b5185e25e)

**Comment by OzoneAsai** [comment]
`pip3 install torch==2.3.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121`
で解決しました。また、どちらかといえば既出だったので、クローズします。
