### ISSUE TITLE
API サーバーが立ち上がらない (Ubuntu)

### ISSUE THREAD

**Issue by ku6ryo** [litagin02/Style-Bert-VITS2#168]
[Runpod](https://www.runpod.io/) のクラウドサーバー (Ubuntu) で API サーバーを立ち上げようとしたところ、以下のエラーがでて立ち上がりませんでした。原因・解決方法がわかれば教えていただきたいです。

```
(new_env) root@7353202850ee:/workspace/Style-Bert-VITS2# python server_fastapi.py
10-04 19:13:30 | DEBUG  | __init__.py:130 | pyopenjtalk worker server started
Error: Failed to update dictionary.
Traceback (most recent call last):
  File "/workspace/Style-Bert-VITS2/style_bert_vits2/nlp/japanese/user_dict/__init__.py", line 145, in update_dict
    pyopenjtalk.mecab_dict_index(str(tmp_csv_path), str(tmp_compiled_path))
  File "/workspace/Style-Bert-VITS2/style_bert_vits2/nlp/japanese/pyopenjtalk_worker/__init__.py", line 46, in mecab_dict_index
    WORKER_CLIENT.dispatch_pyopenjtalk("mecab_dict_index", path, out_path, dn_mecab)
  File "/workspace/Style-Bert-VITS2/style_bert_vits2/nlp/japanese/pyopenjtalk_worker/worker_client.py", line 41, in dispatch_pyopenjtalk
    response = receive_data(self.sock)
  File "/workspace/Style-Bert-VITS2/style_bert_vits2/nlp/japanese/pyopenjtalk_worker/worker_common.py", line 44, in receive_data
    body = __receive_until(sock, data_length)
  File "/workspace/Style-Bert-VITS2/style_bert_vits2/nlp/japanese/pyopenjtalk_worker/worker_common.py", line 35, in __receive_until
    raise ConnectionClosedException("接続が閉じられました")
style_bert_vits2.nlp.japanese.pyopenjtalk_worker.worker_common.ConnectionClosedException: 接続が閉じられました
Traceback (most recent call last):
  File "/workspace/Style-Bert-VITS2/server_fastapi.py", line 52, in <module>
    update_dict()
  File "/workspace/Style-Bert-VITS2/style_bert_vits2/nlp/japanese/user_dict/__init__.py", line 159, in update_dict
    raise e
  File "/workspace/Style-Bert-VITS2/style_bert_vits2/nlp/japanese/user_dict/__init__.py", line 145, in update_dict
    pyopenjtalk.mecab_dict_index(str(tmp_csv_path), str(tmp_compiled_path))
  File "/workspace/Style-Bert-VITS2/style_bert_vits2/nlp/japanese/pyopenjtalk_worker/__init__.py", line 46, in mecab_dict_index
    WORKER_CLIENT.dispatch_pyopenjtalk("mecab_dict_index", path, out_path, dn_mecab)
  File "/workspace/Style-Bert-VITS2/style_bert_vits2/nlp/japanese/pyopenjtalk_worker/worker_client.py", line 41, in dispatch_pyopenjtalk
    response = receive_data(self.sock)
  File "/workspace/Style-Bert-VITS2/style_bert_vits2/nlp/japanese/pyopenjtalk_worker/worker_common.py", line 44, in receive_data
    body = __receive_until(sock, data_length)
  File "/workspace/Style-Bert-VITS2/style_bert_vits2/nlp/japanese/pyopenjtalk_worker/worker_common.py", line 35, in __receive_until
    raise ConnectionClosedException("接続が閉じられました")
style_bert_vits2.nlp.japanese.pyopenjtalk_worker.worker_common.ConnectionClosedException: 接続が閉じられました
10-04 19:13:30 | DEBUG  | __init__.py:147 | pyopenjtalk worker server terminated
10-04 19:13:30 | ERROR  | __init__.py:157 | 接続が閉じられました
```

**Comment by luvwinnie** [comment]
@litagin02 さん，こんにちは。

私も同じ問題が発生しています。

私の方はリモートのUbuntuでやろうとしていますが，うまく，pyopenjtalkが立ち上がりません。
PyopenJTalkのWorkerClientが，リモートでやる場合，どうデバッグすればよいでしょうか？

**Comment by luvwinnie** [comment]
@litagin02 どうやら，[pyopenjtalk](https://github.com/litagin02/pyopenjtalk)がきちんと@litagin02さんのものを使わないと動かないらしいです。

```
Error: Failed to update dictionary.
Traceback (most recent call last):
  File "/misc/Work34/cheesiang_leow/tts/Style-Bert-VITS2/style_bert_vits2/nlp/japanese/user_dict/__init__.py", line 150, in update_dict
    pyopenjtalk.unset_user_dict()
  File "/misc/Work34/cheesiang_leow/tts/Style-Bert-VITS2/style_bert_vits2/nlp/japanese/pyopenjtalk_worker/__init__.py", line 72, in unset_user_dict
    pyopenjtalk.unset_user_dict()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pyopenjtalk' has no attribute 'unset_user_dict'
Traceback (most recent call last):
  File "/misc/Work34/cheesiang_leow/tts/Style-Bert-VITS2/server_editor.py", line 157, in <module>
    update_dict()
  File "/misc/Work34/cheesiang_leow/tts/Style-Bert-VITS2/style_bert_vits2/nlp/japanese/user_dict/__init__.py", line 159, in update_dict
    raise e
  File "/misc/Work34/cheesiang_leow/tts/Style-Bert-VITS2/style_bert_vits2/nlp/japanese/user_dict/__init__.py", line 150, in update_dict
    pyopenjtalk.unset_user_dict()
  File "/misc/Work34/cheesiang_leow/tts/Style-Bert-VITS2/style_bert_vits2/nlp/japanese/pyopenjtalk_worker/__init__.py", line 72, in unset_user_dict
    pyopenjtalk.unset_user_dict()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pyopenjtalk' has no attribute 'unset_user_dict'
```

今後READMEに追加したほうが良いと思います。

**Comment by sabipipe** [comment]
こちら再現しました。requirements.txt を以下のように書き換えて `pip install -r requirements.txt` し、pyopenjtalkのGitHub上の最新版を使わせるようにすると動きました。リリース漏れでしょうか。Windowsでは問題ないのが不思議ですが。

```diff
-pyopenjtalk-dict
+-e git+https://github.com/litagin02/pyopenjtalk.git#egg=pyopenjtalk-dict
```

**Comment by junmoka** [comment]
runpodで同様の事象が発生しました。

runpod環境で稼働しているサービスと、worker_serverのポートが競合していることが原因だと思われます。
WORKER_PORTを「9999」など競合しないポートに変更したところ正常に動作しました。

## worker_serverのポート

style_bert_vits2/nlp/japanese/pyopenjtalk_worker/__init__.py
```python
from style_bert_vits2.nlp.japanese.pyopenjtalk_worker.worker_common import WORKER_PORT
```

style_bert_vits2/nlp/japanese/pyopenjtalk_worker/worker_common.py
```
WORKER_PORT: Final[int] = 7861
```

## runpodの稼働ポート

```
# lsof -i:7861
COMMAND PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
nginx    52 root    8u  IPv4 21037148      0t0  TCP *:7861 (LISTEN)
```

**Comment by sho0120** [comment]
pyopenjtalk.mecab_dict_index()で日本語が含まれたファイルパスが入力されたとき、同様のエラーが出力されることを確認しました。
workspaceまでのフォルダパスに、日本語が含まれていませんか？
