### ISSUE TITLE
uvによるvenvのデフォルトPythonバージョン変更によるインストール不良

### ISSUE THREAD

**Issue by AllAzimuths** [litagin02/Style-Bert-VITS2#184]
現在、インストール用のbatファイル、及びコマンドライン用コマンドを実行するとPython 3.13の環境が作成されますが、ここではその後のコマンドで指定されているバージョンのライブラリ（torch等）がインストール出来ません。
Pythonに触れた事が無い人にはこれを解決するのは難しいので、インストール用コマンドに仮想環境のPythonバージョンを指定する追記をお願いします。

**Comment by AllAzimuths** [comment]
上記を解決しただけでは不足の様です。以下、app.batを実行した際の出力を添付します。

```
Running app.py...

Traceback (most recent call last):
  File "C:\FreeSofts\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\FreeSofts\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\FreeSofts\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\numpy\core\overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed while importing _multiarray_umath: 指定されたモジュールが見つかりません。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\FreeSofts\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\numpy\__init__.py", line 144, in <module>
    from numpy.__config__ import show as show_config
  File "C:\FreeSofts\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\numpy\__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "C:\FreeSofts\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\numpy\core\__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "C:\FreeSofts\Style-Bert-VITS2\Style-Bert-VITS2\venv\Scripts\python.exe"
  * The NumPy version is: "1.26.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: 指定されたモジュールが見つかりません。


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\FreeSofts\Style-Bert-VITS2\Style-Bert-VITS2\app.py", line 4, in <module>
    import gradio as gr
  File "C:\FreeSofts\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "C:\FreeSofts\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "C:\FreeSofts\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 7, in <module>
    from gradio.components.base import Component, FormComponent
  File "C:\FreeSofts\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\FreeSofts\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\gradio\components\annotated_image.py", line 9, in <module>
    import numpy as np
  File "C:\FreeSofts\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\numpy\__init__.py", line 149, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
Press any key to continue . . .
```

**Comment by litagin02** [comment]
初期のbatファイルによるインストールでは、まずPython3.10.11環境がダウンロードされ、次にその内部のpipでuvが構築されるので、Python3.13環境になることはないはずです。

ただコマンドラインでのインストール時には確かに元々が3.13環境だった場合や、Pythonが入っていない場合や、uvでの仮想環境のデフォルトが3.13だった場合はまずそうなので、Pythonバージョンに関する追記を検討します。

> 上記を解決しただけでは不足の様です。以下、app.batを実行した際の出力を添付します。

これについては原因がすぐには分からないため、どのようにインストールを行ったかを教えていただけないでしょうか？

**Comment by AllAzimuths** [comment]
以下、失敗した状況を記述します。
ハードウェア：Xeon E5-2470 v2 ×2、GTX1050Ti ＋ RTX3060
OS：Windows10 Pro 22H2

１：Python3.10、Python3.12がそれぞれインストールされた状態（VSCodeやAnaconda未使用の素のインストール）でbatファイルを実行、上記エラーが表示され失敗

２：１を削除しPython3.10、Python3.12それぞれを通常手順でアンインストールした状態でbatファイルを実行、以下同様

３：２を削除しPython3.10、Python3.12をそれぞれ再びクリーンインストール、今度はGeekUninstallerを用い完全アンインストールした状態でbatファイルを実行、以下同様

４：３を削除しコマンドプロンプトで実行、以下同様

５：作成された仮想環境を立ち上げnumpyやtorchを再インストール、エラー変わらず

６：作成された仮想環境がPython3.13である事を確認、3.10に下げライブラリを入れ直し実行、エラー変わらず

７：６を削除しuvコマンドをwindowsにインストールしPythonのバージョンを指定した上でコマンドプロンプトでインストールを実行、エラー変わらず

８：Windowsをクリーンインストールしてbatファイルを実行、インストール成功

**Comment by litagin02** [comment]
詳細にありがとうございます。
すみません、やはり何が原因かがはっきりとは断言ができないです……すみません。
numpyが何か競合したり古い何かしらのものが残っていたりするのが原因かと思われますが、
何がそれを起こしたかまではこちらからは原因が分かりません。
今まで報告されたことのないエラーなので、何らかの環境依存でのnumpy周辺の整合性が崩れている状態だったのかと思われます。

とりあえずクリーンインストール後はインストール成功したということでよかったですが、いろいろとお手数をおかけしてしまい、また原因も特定できず申し訳ありません。
