### ISSUE TITLE
torch.hub.load error

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [litagin02/Style-Bert-VITS2#35]
![image](https://github.com/litagin02/Style-Bert-VITS2/assets/87591236/2fda752a-7122-4766-9ce3-b284ad174efd)
```
Error: Downloading: "https://github.com/snakers4/silero-vad/zipball/master" to C:\Users\L/.cache\torch\hub\master.zip
Traceback (most recent call last):
  File "F:\LSX_HOME\stylebertinstall\Style-Bert-VITS2\Style-Bert-VITS2\slice.py", line 13, in <module>
    vad_model, utils = torch.hub.load(
  File "F:\LSX_HOME\stylebertinstall\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\torch\hub.py", line 563, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "F:\LSX_HOME\stylebertinstall\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\torch\hub.py", line 257, in _get_cache_or_reload
    with zipfile.ZipFile(cached_file) as cached_zipfile:
  File "zipfile.py", line 1269, in __init__
  File "zipfile.py", line 1336, in _RealGetContents
zipfile.BadZipFile: File is not a zip file
```
```
Error: Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1283, in request
  File "http\client.py", line 1329, in _send_request
  File "http\client.py", line 1278, in endheaders
  File "http\client.py", line 1038, in _send_output
  File "http\client.py", line 976, in send
  File "http\client.py", line 1455, in connect
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\LSX_HOME\stylebertinstall\Style-Bert-VITS2\Style-Bert-VITS2\slice.py", line 13, in <module>
    vad_model, utils = torch.hub.load(
  File "F:\LSX_HOME\stylebertinstall\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\torch\hub.py", line 563, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "F:\LSX_HOME\stylebertinstall\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\torch\hub.py", line 230, in _get_cache_or_reload
    _validate_not_a_forked_repo(repo_owner, repo_name, ref)
  File "F:\LSX_HOME\stylebertinstall\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\torch\hub.py", line 189, in _validate_not_a_forked_repo
    response = json.loads(_read_url(Request(url, headers=headers)))
  File "F:\LSX_HOME\stylebertinstall\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\torch\hub.py", line 172, in _read_url
    with urlopen(url) as r:
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>

```

**Comment by litagin02** [comment]
It seems that Silero VAD zip file is broken.
Check and delete file `C:\Users\L/.cache\torch\hub\master.zip` and  `C:\Users\L/.cache\torch\hub\snakers4_silero-vad_master` directory if exist and please retry.
