### ISSUE TITLE
server_fastapi.pyにエラーが出ました

### ISSUE THREAD

**Issue by shikichrome** [litagin02/Style-Bert-VITS2#51]
![Uploading スクリーンショット 2024-02-10 202806.png…]()

**Comment by OzoneAsai** [comment]
![image](https://github.com/litagin02/Style-Bert-VITS2/assets/56304837/dcbbf8a4-3ce2-4177-81f9-bf096762de70)
なんか読めないんだけど...私だけですかね？

**Comment by litagin02** [comment]
同じくエラー画像は見えません。
また画像だけでなくエラーのテキストも貼っていただけると助かります。

**Comment by shikichrome** [comment]
わかりました
                INFO server_fastapi.py:85 | Loading mode Is...
                   INFO infer.py:19 | Using JP-Extra model
E:¥python¥l ib¥site-packages¥torch¥nn¥uti ls¥weight_norm.py:30: UserWarning: torch.nn.liti Is.weight_norm is deprecated in
avor of torch.nn;uti Is.parametrizations.weight_norm.
  warnings.warn("torch.nn.uti Is.weight_norm is deprecated in favor of torch.nn.uti Is.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "E:¥Style-Bert-VITS2¥Style-Bert-VITS2¥server_fastapi.py", line 86, in <module>
    load_modeIs(mode I_hoIder)
  File "E:¥Style-Bert-VITS2¥Style-Bert-VITS2¥server_fastapi.py", line 62, in load_models
    mode I.Ioad_net_g()
  File "E:¥Style-Bert-VITS2¥Style-Bert-VITS2¥common¥tts_modeI.py", line 59, in load_net_g
    self.net_g = get_net_g(
  File "E:¥Style-Bert-VITS2¥Style-Bert-VITS2¥infer.py", line 39, in get_net_g
    _ = uti Is.Ioad_checkpoint(model_path, net_g, None, skip_optimizer=True)
  File "E:¥Style-Berf-VITS2¥Style-Bert-VITS2¥uti Is.py", I ine 38, in load_checkpoint
    iteration = checkpoint_dict["iteration"]
KeyError: ’ i terat ion’

**Comment by shikichrome** [comment]
> 同じくエラー画像は見えません。 また画像だけでなくエラーのテキストも貼っていただけると助かります。
02-10 20:58:21 | INFO | server _fastapi.py:85 | Loading models..
02-10 20:58:21
INFO
infer.py: 19 | Using JP-Extra model
E:¥python¥l ib¥site-packages¥torchÝnn¥uti ls¥weight_norm.py:30: User₩arning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.uti|s.parametrizations.weight_norm.
Traceback (most recent call last):
File "E:¥Style-Bert-VITS2¥Sty|e-Bert-VITS2¥server_fastapi.py", line 86, in
load models(model holder)
File "E:¥Style-Bert=VITS2¥Style-Bert-VITS2¥server_fastapi.py", line 62, in load models
model. load_net_g()
File "E:¥StyTe-Bert-VITS2¥Style-Bert-VITS2¥common¥tts_model.py", line 59, in load_net_g
self.net g= get_net_g(
File "E:¥Style-Bert-VITS2¥Style-Bert-VITS2¥infer.py", line 39, in get_net_g
utils.load_checkpoint(model_path, net_g, None, skip_optimizer=True)
FiTe "E:¥Sty|e-Bert-VITS2¥Style-Bert-VÍTS2¥utils.py", line 38, in load checkpoint
iteration = checkpoint dict["iteration"]
KevError: 'iteration

**Comment by litagin02** [comment]
model_assetsの中のモデルたちの構造はどのようになっていますか？エラーからはpthファイルが入っているフォルダがあるように思われ、それの読み込みエラーが起きている模様です。
model_assetsの中のディレクトリには、safetensorsファイルとconfig.jsonとstyle_vectors.npyファイルのみをいれるようにしてください。
