### ISSUE TITLE
Can't run pre-process while editor.py  running

### ISSUE THREAD

**Issue by OzoneAsai** [litagin02/Style-Bert-VITS2#72]
```log
Traceback (most recent call last):
  File "C:\WorkSpace\Style-Bert-VITS2\text\user_dict\__init__.py", line 146, in update_dict
    tmp_compiled_path.replace(compiled_dict_path)
  File "pathlib.py", line 1247, in replace
PermissionError: [WinError 5] アクセスが拒否されました。: 'dict_data\\user.dict_compiled-55bbb6a0-47d1-46f4-b1b9-7bbfa713970c.tmp' -> 'dict_data\\user.dic'
Error: Failed to update dictionary.
Traceback (most recent call last):
  File "C:\WorkSpace\Style-Bert-VITS2\text\user_dict\__init__.py", line 146, in update_dict
    tmp_compiled_path.replace(compiled_dict_path)
  File "pathlib.py", line 1247, in replace
PermissionError: [WinError 5] アクセスが拒否されました。: 'dict_data\\user.dict_compiled-b1e14fd9-69ce-4651-bc17-7d7903d036e5.tmp' -> 'dict_data\\user.dic'
Error: Failed to update dictionary.
Traceback (most recent call last):
  File "C:\WorkSpace\Style-Bert-VITS2\text\user_dict\__init__.py", line 146, in update_dict
    tmp_compiled_path.replace(compiled_dict_path)
  File "pathlib.py", line 1247, in replace
PermissionError: [WinError 5] アクセスが拒否されました。: 'dict_data\\user.dict_compiled-8f15d5de-abde-413f-a02a-243a5b76e18a.tmp' -> 'dict_data\\user.dic'

Aborted!

02-26 16:50:33 | ERROR  | webui_train.py:197 | Step 3: preprocessing text failed.
Terminate batch job (Y/N)?
```

**Comment by litagin02** [comment]
報告ありがとうございます。
#71  と共通の原因の問題のためクローズします。
