### ISSUE TITLE
Merge.batのエラー

### ISSUE THREAD

**Issue by OzoneAsai** [litagin02/Style-Bert-VITS2#79]
```log
Traceback (most recent call last):
  File "C:\WorkSpace\Style-Bert-VITS2\webui_merge.py", line 30, in <module>
    model_holder = ModelHolder(assets_root, device)
  File "C:\WorkSpace\Style-Bert-VITS2\common\tts_model.py", line 228, in __init__
    self.refresh()
  File "C:\WorkSpace\Style-Bert-VITS2\common\tts_model.py", line 235, in refresh
    model_dirs = [d for d in self.root_dir.iterdir() if d.is_dir()]
AttributeError: 'str' object has no attribute 'iterdir'
Press any key to continue . . .
```
原因がわからん...Merge.batを実行しただけなのに...変更を書き込んだのはapp.batの--shareだけだから関係なさそうだし...

**Comment by litagin02** [comment]
こちらは内部でModelクラスでPathを使うように変更したことからのバグです
masterブランチ最新版では修正されています。
