### ISSUE TITLE
Error? while training English model

### ISSUE THREAD

**Issue by OzoneAsai** [litagin02/Style-Bert-VITS2#99]
```
Epoch 1(3%)/120:   0%|                                                                                                                                                   | 67/282720 [00:44<43:50:58,  1.79it/s]E0316 00:51:18.149152 15432 _internal.py:96] Error on request:
Traceback (most recent call last):
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\application.py", line 528, in __call__
    return self._app(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\application.py", line 569, in wrapper
    return wsgi_app(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\security_validator.py", line 91, in __call__
    return self._application(environ, start_response_proxy)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\path_prefix.py", line 68, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\experiment_id.py", line 73, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\empty_path_redirect.py", line 43, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\client_feature_flags.py", line 55, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\auth_context_middleware.py", line 38, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\application.py", line 551, in _route_request
    return self.exact_routes[clean_path](environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\werkzeug\wrappers\request.py", line 189, in application
    resp = f(*args[:-2] + (request,))
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\plugins\hparams\hparams_plugin.py", line 121, in get_experiment_route
    json_format.MessageToJson(
TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'
Epoch 1(3%)/120:   0%|                                                                                                                                                   | 70/282720 [00:46<44:20:37,  1.77it/s]E0316 00:51:19.769442  6464 _internal.py:96] Error on request:
Traceback (most recent call last):
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\application.py", line 528, in __call__
    return self._app(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\application.py", line 569, in wrapper
    return wsgi_app(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\security_validator.py", line 91, in __call__
    return self._application(environ, start_response_proxy)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\path_prefix.py", line 68, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\experiment_id.py", line 73, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\empty_path_redirect.py", line 43, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\client_feature_flags.py", line 55, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\auth_context_middleware.py", line 38, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\application.py", line 551, in _route_request
    return self.exact_routes[clean_path](environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\werkzeug\wrappers\request.py", line 189, in application
    resp = f(*args[:-2] + (request,))
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\plugins\hparams\hparams_plugin.py", line 121, in get_experiment_route
    json_format.MessageToJson(
TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'
Epoch 1(3%)/120:   0%|                                                                                                                                                   | 77/282720 [00:50<45:00:25,  1.74it/s]E0316 00:51:23.696123 20820 _internal.py:96] Error on request:
Traceback (most recent call last):
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\application.py", line 528, in __call__
    return self._app(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\application.py", line 569, in wrapper
    return wsgi_app(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\security_validator.py", line 91, in __call__
    return self._application(environ, start_response_proxy)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\path_prefix.py", line 68, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\experiment_id.py", line 73, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\empty_path_redirect.py", line 43, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\client_feature_flags.py", line 55, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\auth_context_middleware.py", line 38, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\application.py", line 551, in _route_request
    return self.exact_routes[clean_path](environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\werkzeug\wrappers\request.py", line 189, in application
    resp = f(*args[:-2] + (request,))
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\plugins\hparams\hparams_plugin.py", line 121, in get_experiment_route
    json_format.MessageToJson(
TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'
Epoch 1(5%)/120:   0%|                                                                                                                                                  | 122/282720 [01:15<43:55:23,  1.79it/s]E0316 00:51:49.479738  4548 _internal.py:96] Error on request:
Traceback (most recent call last):
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\application.py", line 528, in __call__
    return self._app(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\application.py", line 569, in wrapper
    return wsgi_app(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\security_validator.py", line 91, in __call__
    return self._application(environ, start_response_proxy)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\path_prefix.py", line 68, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\experiment_id.py", line 73, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\empty_path_redirect.py", line 43, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\client_feature_flags.py", line 55, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\auth_context_middleware.py", line 38, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\application.py", line 551, in _route_request
    return self.exact_routes[clean_path](environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\werkzeug\wrappers\request.py", line 189, in application
    resp = f(*args[:-2] + (request,))
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\plugins\hparams\hparams_plugin.py", line 121, in get_experiment_route
    json_format.MessageToJson(
TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'
Epoch 1(5%)/120:   0%|                                                                                                                                                  | 123/282720 [01:16<43:53:51,  1.79it/s]E0316 00:51:49.808524 19608 _internal.py:96] Error on request:
Traceback (most recent call last):
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\werkzeug\serving.py", line 323, in execute
    application_iter = app(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\application.py", line 528, in __call__
    return self._app(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\application.py", line 569, in wrapper
    return wsgi_app(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\security_validator.py", line 91, in __call__
    return self._application(environ, start_response_proxy)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\path_prefix.py", line 68, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\experiment_id.py", line 73, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\empty_path_redirect.py", line 43, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\client_feature_flags.py", line 55, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\auth_context_middleware.py", line 38, in __call__
    return self._application(environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\backend\application.py", line 551, in _route_request
    return self.exact_routes[clean_path](environ, start_response)
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\werkzeug\wrappers\request.py", line 189, in application
    resp = f(*args[:-2] + (request,))
  File "C:\WorkSpace\Style-Bert-VITS2\Style-Bert-VITS2\venv\lib\site-packages\tensorboard\plugins\hparams\hparams_plugin.py", line 121, in get_experiment_route
    json_format.MessageToJson(
TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'
Epoch 1(7%)/120:   0%|                                                                                                                                                  | 177/282720 [01:46<44:23:10,  1.77it/s]
```
再現のための質問はどうぞ...

**Comment by OzoneAsai** [comment]
https://github.com/litagin02/Style-Bert-VITS2/issues/100
状況はこれです

**Comment by litagin02** [comment]
ではこちらのエラーも解決したということでよろしいでしょうか？

**Comment by OzoneAsai** [comment]
えっとー(コンソールを確認...)
はい、出てません。解決しました
